#!/bin/bash

BASE_FILENAME='wordpress-cli-installer'
SHELL_SCRIPT="${BASE_FILENAME}.sh"
PHP_SCRIPT="${BASE_FILENAME}.php"
PHP_OPTIONS=''

cat > $SHELL_SCRIPT <<EOF
#!/bin/bash

#THIS FILE IS AUTOGENERATED, DO NOT EDIT IT
#EDIT ${PHP_SCRIPT}, THEN RUN $(basename $0) TO MAKE CHANGES

if [ -x /usr/bin/php-cli ]; then
    PHP=/usr/bin/php-cli
elif [ -x /usr/bin/php ]; then
    PHP=/usr/bin/php
else
    echo "No suitable PHP interpreter found"
    exit 129
fi
\$PHP $PHP_OPTIONS -- "\$@" <<EOF
EOF

php -w $PHP_SCRIPT | sed 's/\$/\\$/g' >> $SHELL_SCRIPT

echo >> $SHELL_SCRIPT
echo 'EOF' >> $SHELL_SCRIPT
cat >> $SHELL_SCRIPT <<EOF
if [ \$? -eq 128 ]; then
  exit 0
elif [ \$? -eq 0 ]; then
  exit 99
else
  exit \$?
fi
EOF
